### PR TITLE
Update to support mssql/sql server

### PR DESCRIPTION
**Pull request by davidpham87**
The MS SQL syntax differs a bit from mysql. Following this comment on [stackoverflow](https://stackoverflow.com/questions/6520999/create-table-if-not-exists-equivalent-in-sql-server#comment80047630_6521016), I added a new case to the dbtype to support datahike with microsoft sql.

### CODE REVIEW

**Comment by alekcz** [comment]
@davidpham87 Thanks for adding this. I'll have a look this evening.

**Comment by alekcz** [comment]
@davidpham87 do you have the bandwidth to add mssql to the docker-compose script and add a test suite for it? 
If not I can do it over the weekend.

**Comment by davidpham87** [comment]
@alekcz I am sorry, my schedule won't allow me to help you before next week. Moreover, my wife could give birth anytime soon.

**Comment by alekcz** [comment]
@davidpham87 no stress. According to my notes, the birth of a kid is slightly more important than a patch 😜 All the best!

**Pull request merged**
